### ISSUE TITLE
tutorial / smoke flip books

### ISSUE THREAD

**Issue by tastez** [keijiro/SixWaySmokeTest#1]
Hi kzr, was this project part of a tutorial? Also wondering if flipbooks are missing on purpose

**Comment by keijiro** [comment]
> was this project part of a tutorial?

No, this is just for testing purposes.

> Also wondering if flipbooks are missing on purpose

Yes, because the license doesn't allow redistributing them.

**Comment by tastez** [comment]
it looks like its part of this https://www.youtube.com/watch?v=319HikAOC3g which is very helpful
